apiVersion: v2
name: k8s-app-hpa
version: 1.0.0
description: Production-grade application deployed with HPA and AWS LoadBalancer Controller.

type: application
appVersion: "1.0.0"
keywords:
  - kubernetes
  - eks
  - hpa
  - autoscaling